bump Dockerfile python to 3.10
The current image errors with the following because match is only in python >= 3.10:

Traceback (most recent call last):                                                            
  File "/TwitchDropsMiner/main.py", line 28, in <module>                                          from twitch import Twitch                                                                 
  File "/TwitchDropsMiner/twitch.py", line 39, in <module>                                        from gui import GUIManager                                                                  File "/TwitchDropsMiner/gui.py", line 2202                                                  
    match name:                                
          ^                                    
SyntaxError: invalid syntax